### ISSUE TITLE
Mass Editor can't edit "Subject" and "Due Date" on Activity list?

### ISSUE THREAD

**Issue by a824355732** [xgeek-net/salesforce-mass-editor#28]
Mass Editor can't edit "Subject" and "Due Date" on Activity list, which is "https://eu14.salesforce.com/00U". The item is grey. Can you fix the problem, pleaseeeeee? I would be most grateful.

**Comment by a824355732** [comment]
Also, can you please add mass edit support on account target list? Please?

**Comment by xgeek-net** [comment]
Hi, @a824355732 , will check it soon.

**Comment by a824355732** [comment]
Mass Editor can't edit "Subject" and "Event Record Type" on Activity list, which is on "https://eu14.salesforce.com/00U". Pleaseeeee fix it, my life is hell without your mass editor.

**Comment by xgeek-net** [comment]
Hi, @a824355732 

Sorry for your waiting. This issue is fixed in latest version(v3.1.5).
Now you can edit "Subject", "Due Date" on task list and "Event Record Type" on  event list with below url. (It's still not perfect on Record Type lookup but you can input Record Type value and save it directly)

- Tasks:
https://eu14.salesforce.com/00T

- Events:
https://eu14.salesforce.com/00U

Thank you for loving Mass Editor!
